### ISSUE TITLE
Domains with Even values of m can not form junctions on their right sides!

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#17]
Weird!

**Comment by 404Wolf** [comment]
Note to self: appears to be an alignment issue.

![image](https://user-images.githubusercontent.com/108041238/214454037-5aa21284-bdd8-472a-93a1-38775e963540.png)

**Comment by 404Wolf** [comment]
Update: I think I've tracked this down. In structures>domains>domains.py under the strands() class, where the NEMids and Nucleosides are initially computed, if computes the NEMids and nucleosides at once. Since there are some NEMids at x=1 and some nucleosides at x=1 (x=1 as an example), when domain 2 checks for the greatest x coord of domain 1, it may lock onto a nucleoside. This is (probably) a very annoying bug to fix, but I will try to see what I can do.

**Comment by 404Wolf** [comment]
Another Update: this is a more profound bug. When determining which NEMid to pick up from for the next domain, it always checks the zeroed strand of the previous double helix, without regard for the left helix joint:

`initial_z_coord = all_zeroed_strand_z_coords[-1][:B][ np.argmax(all_zeroed_strand_x_coords[-1])]`

**Comment by 404Wolf** [comment]
Complete side view overhaul has solved this issue!
