### ISSUE TITLE
Self-Complementary Sequences

### ISSUE THREAD

**Issue by DNAcer** [NATuG3/NATuG3#19]
Now that we can add linkages, we have the possibility of having a situation where one part of a strand is complementary to another part of the same strand. Thus we can't simply assign sequences independently to all the bases on a single strand. For each base assigned, we need to check whether the complementary base is on the same strand, and if it is, then we need to assign that base consistently.

**Comment by DNAcer** [comment]
Now that we can add linkages, we have the possibility of having a situation where one part of a strand is complementary to another part _of the same strand_. Thus we can't simply assign sequences independently to all the bases on a single strand. For each base assigned, we need to check whether the complementary base is on the same strand, and if it is, then we need to assign that base consistently.

**Comment by 404Wolf** [comment]
@DNAcer 
I've resolved this problem in the `mating_fixes` branch! Now, the sequence editor dialog does not auto complement bases that do not have mates, and bases are only assigned mates within overlapping segments of their body count region. Let me know if it works as expected for you, and I can push the changes.

**Comment by DNAcer** [comment]
Hi Wolf,

First impression is that this is running extremely slowly, but that might
be something wonky with my computer.

Anyway, there still seems to be a problem with self-complementary segments
not being complementary properly.

Also, where do we control the length of the linkages again? With my
computer running NATug so slowly, I can't find that control.

Oh, by the way, I can't find the paper draft you have in the directory you
linked me to. Is it possible you haven't shared/pushed the file?

Thanks,
Bill

**Comment by 404Wolf** [comment]
@DNAcer 
I'm not sure why NATuG is running slowly for you, it seems the same speed for me. Perhaps we can debug that specific problem Tuesday, since that sounds like a computer specific problem. I invited you a while back to join the "NATuG3" organization as an owner, but I think you missed the email, so I just sent another invite. The paper is a private repository within the organization, so you need to accept the invite and be logged in. The length of the linkages can be set by clicking on the linkage. I just realized that this thread is for self-complementary sequences, which are indeed still not working, so that's my bad--the problem I fixed was length mismatched (body count/top count/bottom count) strands mating correctly, and the sequence editor complement display area.

**Comment by 404Wolf** [comment]
Self complementary sequences now work and I've merged the change to main! I'm going to close this issue.
